### ISSUE TITLE
Discuss and set team goals and expectations

### ISSUE THREAD

**Issue by Caitacular** [chingu-voyage3/geckos-34#2]
We need to figure out when everyone is available and what everyone expects to accomplish.

**Comment by ghost** [comment]
I am available Sun-Fri 9am-5pm PST!

**Comment by mrbrackins** [comment]
The earlier the better for me. 8:00AM -10:00AM would be the golden hours.

**Comment by sanchezl391** [comment]
How many hours a week will you be dedicating to this project?

For the next two weeks: Available Mon, Wed, Fri Sat, Sun at any time. 
After the next two weeks: Available at any time

**Comment by Caitacular** [comment]
Oh jeez, that's a bit rough! I'm available from 10AM to 10PM for sure most days, but I'm a night owl so I'll likely be doing lots of my work late at night. As long as I'm awake I can answer messages, though. 
I'll probably dedicate at least 2hrs a weekday to this, and at least 4hrs a day on the weekend for this project, depending on what's needed and my free time.

**Comment by Caitacular** [comment]
Real quick, what time zones @mrbrackins and @sanchezl391? Also, what time does all day begin for you @sanchezl391? I'm MST, myself.

**Comment by sanchezl391** [comment]
I'm mountain time

**Comment by sanchezl391** [comment]
My day begins at 5 am and 8 am.

**Comment by mrbrackins** [comment]
PST
